/*
 * This source file was generated by the Gradle 'init' task
 */
package api.books.test;

import org.testng.annotations.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

class AppTest {
    
    @Test
    public void getRickAndMorty(){
        given()
            .baseUri("https://rickandmortyapi.com/api")
        .when()
            .get("/character/1")
        .then()
            .statusCode(200)
            .body("name", equalTo("Rick Sanchez"))
            .body("status", equalTo("Alive"))
            .body("species", equalTo("Human"))
            .body("gender", equalTo("Male"));
    }

}
